apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine3otimized
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: machine3otimized
  template:
    metadata:
      labels:
        app: machine3otimized
    spec:
      containers:
        - name: machine3otimized
          image: aguiarzx/machine3otimized:latest
          env:
            - name: CSV_PATH
              value: "/app/metrics.csv"
            - name: UPDATE_INTERVAL
              value: "5"  
          ports:
            - containerPort: 8000
