apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine2
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: machine2
  template:
    metadata:
      labels:
        app: machine2
    spec:
      containers:
        - name: machine2
          image: aguiarzx/machine2:latest  
          env:
            - name: CSV_PATH
              value: "/app/metrics.csv"
            - name: UPDATE_INTERVAL
              value: "5"  
          ports:
            - containerPort: 8000
