apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine3
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: machine3
  template:
    metadata:
      labels:
        app: machine3
    spec:
      containers:
        - name: machine3
          image: aguiarzx/machine3:latest  
          env:
            - name: GPU_ID
              value: "GPU_0"
            - name: CSV_PATH
              value: "/app/metrics.csv"
            - name: UPDATE_INTERVAL
              value: "5"  
          ports:
            - containerPort: 8000
