apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: machine4-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: machine4
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: "8000"
      path: /
      interval: 5s